name: churpay-api
region: nyc
services:
  - name: api
    # Non-prod/staging spec. Production runs on Droplet+PM2+Nginx.
    # Use "/" when churpay-api is its own repository root.
    source_dir: /churpay-api
    github:
      repo: YOUR_GITHUB_ORG/YOUR_REPO
      branch: main
      deploy_on_push: false
    build_command: npm ci --omit=dev
    run_command: npm start
    environment_slug: node-js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
      initial_delay_seconds: 15
      period_seconds: 20
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
        type: GENERAL
      - key: PORT
        value: "8080"
        type: GENERAL
      - key: DATABASE_URL
        value: ${DATABASE_URL}
        type: SECRET
      - key: JWT_SECRET
        value: ${JWT_SECRET}
        type: SECRET
      - key: PUBLIC_BASE_URL
        value: https://api.example.com
        type: GENERAL
      - key: PAYFAST_MODE
        value: live
        type: GENERAL
      - key: PAYFAST_MERCHANT_ID
        value: ${PAYFAST_MERCHANT_ID}
        type: SECRET
      - key: PAYFAST_MERCHANT_KEY
        value: ${PAYFAST_MERCHANT_KEY}
        type: SECRET
      - key: PAYFAST_PASSPHRASE
        value: ${PAYFAST_PASSPHRASE}
        type: SECRET
      - key: PAYFAST_RETURN_URL
        value: https://api.example.com/api/payfast/return
        type: GENERAL
      - key: PAYFAST_CANCEL_URL
        value: https://api.example.com/api/payfast/cancel
        type: GENERAL
      - key: PAYFAST_NOTIFY_URL
        value: https://api.example.com/webhooks/payfast/itn
        type: GENERAL
      - key: APP_DEEP_LINK_BASE
        value: churpaydemo://payfast
        type: GENERAL
      - key: PAYFAST_APP_FALLBACK_URL
        value: https://www.churpay.com
        type: GENERAL
      - key: PGSSLINSECURE
        value: "false"
        type: GENERAL
      - key: TRUST_PROXY
        value: "true"
        type: GENERAL
      - key: TRUST_PROXY_HOPS
        value: "1"
        type: GENERAL
      - key: CORS_ORIGINS
        value: https://www.churpay.com,https://churpay.com
        type: GENERAL
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
        type: GENERAL
      - key: RATE_LIMIT_MAX
        value: "300"
        type: GENERAL
      - key: AUTH_RATE_LIMIT_WINDOW_MS
        value: "900000"
        type: GENERAL
      - key: AUTH_RATE_LIMIT_MAX
        value: "30"
        type: GENERAL
